configserver: true

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${server.port:8080}}
  client:
    serviceUrl:
      defaultZone: ${vcap.services.service-registry.credentials.uri:http://127.0.0.1:8761}/eureka/

---
spring:
  profiles: cloud
  cloud:
    services:
      registrationMethod: route
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80

---
spring:
  profiles: xyz
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
