spring:
  oauth2:
    sso:
      home:
        secure: false
        path: /,/**/*.html
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: myclient
      clientSecret: myclientsecret
    resource:
      userInfoUri: http://localhost:9999/uaa/user
